### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by oniagba** [ConsenSys-archive/ganache-ui#5476]
I opened the ganache GUI, and then I clicked events - and boom this error message pops up, it has been doing since every time I click on events.

PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\index.js:76:29)
```

**Comment by jeffsmale90** [comment]
Thanks for opening the issue. Can you please try this in the latest release? We fixed this in v2.7.1 [https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.1](https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.1)

Thanks!
