### ISSUE TITLE
Leave blank for default sets to 0

### ISSUE THREAD

**Issue by darioAnongba** [ConsenSys-archive/ganache-ui#662]
## Expected Behavior
In the Settings --> Chain page, when setting the gas limit and gas price to blank (no input), the values should be set to the default ones

## Current Behavior
The gas limit and gas price are set to 0

## Possible Solution
Bug surely happens because of either setting the initial state to 0 or because of the use of the "number" type in HTML5 that will return 0 if left blank.

## Steps to Reproduce (for bugs)

1. Initiate ganache
2. Open Setttings --> Chain
3. Delete values and click Save and Restart
4. Check that gas price and gas limit are 0

## Context
The gas price and gas block limit being dynamic, it is difficult to find the default values on the web.
 
## Your Environment
* Version used: 1.1
* Operating System and version: Windows 10

**Comment by seesemichaelj** [comment]
Thanks @darioAnongba for reporting this!

I'll try to fit this one in somewhere; in the meantime, if someone wants to try to tackle this issue and submit a PR, it should be pretty simple! Thanks!

**Comment by jgwashburn** [comment]
@seesemichaelj  I would be motivated to work on this one - 
Does anyone have a link or two which would give an idea in terms of where in the repo to start looking, in terms of finding a fix? Thanks

**Comment by seesemichaelj** [comment]
@jgwashburn https://github.com/trufflesuite/ganache/blob/develop/src/Components/Config/ConfigScreens/ChainScreen.js is the file which serves the HTML/React for that value. In there is an onChange reference to `this.props.validateChange`. That function is here: https://github.com/trufflesuite/ganache/blob/develop/src/Components/Config/ConfigScreen.js#L139

**Comment by jwlivongo** [comment]
Thanks @seesemichaelj

**Comment by jgwashburn** [comment]
thanks @seesemichaelj

**Comment by brannondorsey** [comment]
I can confirm that this issue persists in v1.2.0 on Ubuntu. That's not at all surprising considering that this project is built with Electron, but I figured I'd mention it nonetheless. What's the status on this? Is someone actively working on a fix?

**Comment by jwlivongo** [comment]
@brannondorsey sorry I have not been able to really work on it. I took a look, and it turned out that I will first need to learn Electron framework and set up debug environment, for me to resolve an issue like this.  So if anyone else wants to tackle it, please feel free.

**Comment by seesemichaelj** [comment]
@brannondorsey in addition to @jwlivongo none of the Truffle dev's are currently working this; our plates are currently really full with some exciting new features, and we haven't gotten a chance to look at this yet.

I suspect this to be easy; feel free to submit a PR!

I'm guessing this is an issue with using the react `type='number'` attribute which is defaulting blank to 0 or something similar. Perhaps there is a "allow blank/null values" option.

**Comment by larsnolden** [comment]
The default values for `settings.server.gasLimit` and `settings.server.gasPrice` used in the Chain Settings component are not being set right now.

@seesemichaelj , can you please confirm that the default values should be the following.
Gas Price: 20000000000
Gas Limit: 6721975
If so, I will add these values to the initial settings in `Services/Setting.js`.

**Comment by benjamincburns** [comment]
After some conversation with @seesemichaelj (prompted by @xitter's PR for this issue), I realized that the underlying structures we have in place for expressing settings and from reading them back from the chain process are a bit wonky - that needs clean-up before this issue can be properly addressed. As a result, I'm going to take this one on myself.

**Comment by benjamincburns** [comment]
For anyone reading along, see my comments on the PR in question here: https://github.com/trufflesuite/ganache/pull/885#issuecomment-416313107
